* Buffer Stacker
  A neovim plugin that keeps buffers arranged in the order they're visited.
  It provides commands to navigate to the next and previous buffers in this order.
  There is a command to print a list of the buffers, much like ~:ls~.
  Finally, there is a telescope picker.

** Rationale
   Having used [[https://github.com/doomemacs/doomemacs][doom emacs]] for many years for writing, I became used to expecting the previously entered buffer to be navigable as the previous buffer via ~:bp~.
   However, neovim orders buffers by their buffer number.

** Installation
   With [[https://github.com/folke/lazy.nvim][lazy.nvim]]:
   #+begin_src lua
   return {
     {
       "davidrambo/buffer-stacker.nvim",
       dependencies = {
         "nvim-telescope/telescope.nvim",
       },
       config = function()
         vim.keymap.set("n", "<leader>bn", "<cmd>BufstackerNext<cr>", { desc = "Next stacked buffer" })
         vim.keymap.set("n", "<leader>bp", "<cmd>BufstackerPrev<cr>", { desc = "Previous stacked buffer" })
         vim.keymap.set("n", "<leader>bl", "<cmd>BufstackerLs<cr>", { desc = "List stacked buffers" })
         vim.keymap.set("n", "<leader>,", function()
           require("buffer-stacker.telescope").bufpicker({
             theme = "ivy",
             ignore_current_buffer = false,
             sort_by_path = false,
           })
         end, { desc = "Pick stacked buffer" })
       end,
     },
   }
   #+end_src

** Usage
   The provided installation snippet sets keymaps for all three commands: ~BufstackNext~, ~BufstackPrev~, and ~BufstackLs~.
   Open and close files as before and enjoy the intuitive ordering of buffers as you visit them.

   Note that you do not need to navigate the buffers using the provided commands, as an autocommand for ~BufEnter~ updates the stack.
   Likewise, there is no provided command for killing a buffer.
   Instead, an autocommand for ~BufDelete~ updates the stack when a buffer is deleted.

*** Telescope Picker
    The telescope picker has three options:
    - ~theme~: ivy, dropdown, cursor
    - ~ignore_current_buffer~: set to true if you don't want the current buffer to be included at the bottom of the list
    - ~sort_by_path~: set to true if you want to fuzzy search the entire path name, false for only the filename

** Similar Projects
   There are several plugins that have the same motivation, and they all seem to do it a bit differently.
   When I started using neovim several years ago, I looked for a plugin like this and did not find one.
   I finally sat down to code up my own, and I ought to have looked again before doing so!
   
   - There's [[https://github.com/BibekBhusal0/bufstack.nvim/tree/master][bufstack.nvim]], which is a fork of:
   - [[https://github.com/bloznelis/buftrack.nvim][buftrack.nvim]]
   - [[https://github.com/tripplyons/stacker.nvim/tree/main][stacker.nvim]]
