* Buffer Stacker
  A neovim plugin that keeps buffers arranged in the order they're visited.
  It provides commands to navigate to the next and previous buffers in this order.
  At the moment, there is a command to print a list of the buffers, much like ~:ls~.
  In the future, I'd like to integrate [[https://github.com/nvim-telescope/telescope.nvim][telescope]] to list and pick buffers from the stack.

** Rationale
   Having used [[https://github.com/doomemacs/doomemacs][doom emacs]] for many years for writing, I became used to expecting the previously entered buffer to be navigable as the previous buffer via ~:bp~.
   However, neovim orders buffers by their buffer number.

** Installation
   With [[https://github.com/folke/lazy.nvim][lazy.nvim]]:
   #+begin_src lua
   return {
       "davidrambo/buffer-stacker.nvim"
       config = function()
           vim.keymap.set('n', '<leader>bn', '<cmd>BufstackerNext<cr>', { desc = 'Next stacked buffer' })
           vim.keymap.set('n', '<leader>bp', '<cmd>BufstackerPrev<cr>', { desc = 'Previous stacked buffer' })
           vim.keymap.set('n', '<leader>bl', '<cmd>BufstackerLs<cr>', { desc = 'List stacked buffers' })
       end
   }
   #+end_src

** Usage
   The provided installation snippet sets keymaps for all three commands: ~BufstackNext~, ~BufstackPrev~, and ~BufstackLs~.
   Open and close files as before and enjoy the intuitive ordering of buffers as you visit them.

   Note that you do not need to navigate the buffers using the provided commands, as an autocommand for ~BufEnter~ updates the stack.
   Likewise, there is no provided command for killing a buffer.
   Instead, an autocommand for ~BufDelete~ updates the stack when a buffer is deleted.

** Similar Projects
   There are several plugins that have the same motivation, and they all seem to do it a bit differently.
   When I started using neovim several years ago, I looked for a plugin like this and did not find one.
   I finally sat down to code up my own, and I ought to have looked again before doing so!
   
   - There's [[https://github.com/BibekBhusal0/bufstack.nvim/tree/master][bufstack.nvim]], which is a fork of:
   - [[https://github.com/bloznelis/buftrack.nvim][buftrack.nvim]]
   - [[https://github.com/tripplyons/stacker.nvim/tree/main][stacker.nvim]]
